stages:          # List of stages for jobs, and their order of execution
  - analysis
  - build
  - test
  - deploy

.build_matrix: &build_matrix
  parallel:
    matrix:
      - COMPILER: ["clang", "gcc"]
        VARIANT: ["debug", "release", "dist"]

static-analysis-job:
  stage: analysis
  script:
    - cppcheck app lib tests
    # add clang-tidy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - cmake --preset=linux-$COMPILER-$VARIANT
    - cmake --build --preset=linux-$COMPILER-$VARIANT
  <<: *build_matrix

unit-test-job:
  stage: test
  before_script:
    - cmake --preset=linux-$COMPILER-$VARIANT
    - cmake --build --preset=linux-$COMPILER-$VARIANT
  script:
    - ctest --preset=linux-$COMPILER-$VARIANT
  <<: *build_matrix
